apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: ecommerce-service-rd
      containers:
        - name: user-service
          image: us.gcr.io/fair-portal-451506-u2/user-service:11
          ports:
          - containerPort: 8081
